# Generated by Django 5.1.1 on 2024-10-18 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0003_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
